### PR TITLE
Update clang-tidy rules for Lightning builds under aarch64

### PR DESCRIPTION
**Pull request by mlxd**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [x] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [x] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [x] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:** More recent versions of clang-tidy are less permission than those used for the general wheel builders. This PR aims to allow us to use `clang-tidy-16` on platforms such as aarch64. This will also serve as the base to update the clang-tidy rules to a unified format across all repos in 2024.

**Description of the Change:** Removes redundant clang-tidy config files, silences unneeded warnings, and makes source changes to allow clang-tidy passes where useful.

**Benefits:** Better support for clang-tidy across newer platforms.

**Possible Drawbacks:**

**Related GitHub Issues:** Also resolves https://github.com/PennyLaneAI/pennylane-lightning/issues/560

### CODE REVIEW

**Review by vincentmr — APPROVED** [review]
I like all the constant definitions. Looks good to me, thanks @mlxd .

**Review by AmintorDusko — COMMENTED** [review]
Hi @mlxd, do you know why we are observing a drop in coverage?

**Comment by mlxd** [comment]
> Hi @mlxd, do you know why we are observing a drop in coverage?

I think this is just due to a reduced line count again --- I don't think any of the test infrastructure changes here, so I'd call it a false flag.

**Review by AmintorDusko — APPROVED** [review]
Thank you for that!

**Comment by vincentmr** [comment]
> Hi @mlxd, do you know why we are observing a drop in coverage?

Given the %'s, I would say it is because parallel-GPU tests are not run.

**Comment by AmintorDusko** [comment]
[sc-50799]

**Comment by AmintorDusko** [comment]
`Testing (Windows) / C++ tests (Windows) (windows-latest, lightning_qubit) (pull_request) ` is hanging and failing after the time limit (30 min). I will test again later.

**Pull request merged**
