### PR TITLE
Improved coverage report for codebase

### PR DESCRIPTION
**Pull request by mlxd**
**Context:** The new C++ code coverage CI checks have reported many areas with low test coverage. 

**Description of the Change:** This updates test coverage of the codebase.

**Benefits:** Improved safety and testing.

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by mlxd — COMMENTED** [review]
Nothing to add from me, nice work folks.

I will try to fix the last remaining percentage on adjoint diff.

**Review by chaeyeunpark — APPROVED** [review]
Hi @maliasadi @mlxd, all looks great! Thanks for your work. I want to leave `DynamicDispatcher.hpp` at the moment as there will be lots of changes in a subsequent PR.

**Comment by chaeyeunpark** [comment]
I think we need to close and reopen the PR to activate GH actions...

**Comment by chaeyeunpark** [comment]
@mlxd Can we merge this PR?

**Comment by mlxd** [comment]
> @mlxd Can we merge this PR?

I think the 75% cov may be too low. I haven't been able to get back into this yet. I'll try to get this improved today.

**Comment by mlxd** [comment]
> > @mlxd Can we merge this PR?
> 
> I think the 71% cov may be too low. I haven't been able to get back into this yet. I'll try to get this improved today.

NVM, scratch that. I looked at the wrong metric. Happy to merge this as is.

**Pull request merged**
