### PR TITLE
Fix Python compiled module linkage and path under Windows

### PR DESCRIPTION
**Pull request by mlxd**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [x] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [x] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [x] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:** Under Windows, CMake was not finding the correct version of Python to compile the wheels against. This was due to the incorrectly named `-DPYTHON_EXECUTABLE` flag, which should have been `-DPython_EXECUTABLE`. In addition, the compiled module path was incorrect in the resulting Windows wheel, and required either updating the `PYTHONPATH` environment variable, or a move of the modules to ensure Lightning worked on the OS.

**Description of the Change:** This PR fixes the Python version found by CMake, and moves the compiled module location in the resulting wheels to prevent the need for a user to update PYTHONPATH or manually move the resulting modules.

**Benefits:** Fixes Windows wheels for Lightning.

**Possible Drawbacks:**

**Related GitHub Issues:** https://github.com/PennyLaneAI/pennylane-lightning/issues/398

### CODE REVIEW

**Comment by mlxd** [comment]
To ensure testability, I will merge the conflicting files and undo once all test and comments are resolved for the release.

**Review by AmintorDusko — APPROVED** [review]
Nice work, @mlxd!
Thank you for the quick fix!

**Review by multiphaseCFD — APPROVED** [review]
Thanks Lee for the nice work!

**Review by chaeyeunpark — APPROVED** [review]
Thanks @mlxd for fixing this. I also installed wheels using Windows+conda, which works well.

**Review by mlxd — COMMENTED** [review]
Updating for merge onto master. Release tagged as v0.28.1_release

**Pull request merged**
