### PR TITLE
Update ALL ubuntu based workflows to use large runners (no label)

### PR DESCRIPTION
**Pull request by rashidnhm**
**Context:** Lightning uses a large amount of the runner pool, this PR ports lightning to using the large runner pool all the time (no label necessary).

**Description of the Change:**
`determine-workflow-runner` was removed, the large runner pool is verbatim used wherever necessary.

**Benefits:**
More storage space available to workflows (150GB vs 15GB of standard runners)

**Possible Drawbacks:**
Huge cost implications, but we will need to monitor and see how it goes!

**Related GitHub Issues:**
[sc-76978](https://app.shortcut.com/xanaduai/story/76978/move-lightning-over-to-using-large-runners-all-the-time)

### CODE REVIEW

**Review by maliasadi — COMMENTED** [review]
Awesome! Thanks @rashidnhm!
Can we remove the GitHub `urgent` label?
Don't forget to add a changelog entry for this PR.

**Review by LuisAlfredoNu — APPROVED** [review]
Thank you @rashidnhm 
Good runner simplification.
Just one question. Is it possible to use the [GPU large runner](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#specifications-for-gpu-larger-runners) to run more GPU workflows? :thinking:

**Review by AmintorDusko — APPROVED** [review]
This is great! Thank you very much, @rashidnhm!

**Comment by rashidnhm** [comment]
> Thank you @rashidnhm Good runner simplification. Just one question. Is it possible to use the [GPU large runner](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#specifications-for-gpu-larger-runners) to run more GPU workflows? 🤔

We are using self-hosted GPU runners on AWS. From my knowledge the GitHub GPU runners are using Nvidia Tesla T4, which are older and less performant than the current Nvidia A10G that we use.

**Comment by rashidnhm** [comment]
Hello @maliasadi @LuisAlfredoNu @AmintorDusko 

I wonder if this is good to merge? I do see a codefactor failure and I am wondering if that's a known bug or something that needs addressing?

**Comment by AmintorDusko** [comment]
> Hello @maliasadi @LuisAlfredoNu @AmintorDusko
> 
> I wonder if this is good to merge? I do see a codefactor failure and I am wondering if that's a known bug or something that needs addressing?

Hey @rashidnhm, you are good to go! This is one more of the codecov's flukes.

**Pull request merged**
