### PR TITLE
Delete references to the removed `QubitStateVector` class

### PR DESCRIPTION
**Pull request by andrijapau**
**Context:**

Completing the deprecation cycle of `QubitStateVector` (see https://github.com/PennyLaneAI/pennylane/pull/6525)

**Description of the Change:**

Removed all references to the deprecated source code.

[sc-77482]

### CODE REVIEW

**Review by lillian542 — COMMENTED** [review]
Left a few suggestions regarding the tests, see what you think :)

**Review by AmintorDusko — COMMENTED** [review]
Thank you for your nice work. Could you please check your PR formatting?
Also, please fill out the changelog. :slightly_smiling_face:

**Review by AmintorDusko — APPROVED** [review]
Great work! Thank you!

**Review by lillian542 — APPROVED** [review]
🎉

**Comment by albi3ro** [comment]
Looking over the indirect changes on code cov, I think codecov is just misbehaving as it sometimes does.  We can try just rerunning the CI and seeing if that fixes it, and if not, we could even potentially override.

It makes it look like we've removed *All* lightning tensor device tests somehow.  Initializing `lightning.tensor` is somehow no longer covered.  Which seems wrong.  So I would say codecov is just being wonky in this case.

**Pull request merged**
