### PR TITLE
Add the RTLD_NODELETE flag to dlopen

### PR DESCRIPTION
**Pull request by multiphaseCFD**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [x] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

There are segfault issue for finite-shot hermitians tests with Catalyst on arm64-macos. It looks like closing `libscipy_openblas.dylib` has a side effect that leads to the segfault and using `RTLD_NODELETE` mitigates that.

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**
[sc-80901]

### CODE REVIEW

**Comment by dime10** [comment]
> There are segfault issue for shor algorithm tests with Catalyst on arm64-macos. It looks like closing libscipy_openblas.dylib has a side effect that leads to the segfault and using RTLD_NODELETE mitigates that.

I think the current issue only appears when running finite-shot hermitians, so not necessarily related to the original problem found with Shor.

**Review by erick-xanadu — APPROVED** [review]

**Comment by multiphaseCFD** [comment]
> > There are segfault issue for shor algorithm tests with Catalyst on arm64-macos. It looks like closing libscipy_openblas.dylib has a side effect that leads to the segfault and using RTLD_NODELETE mitigates that.
> 
> I think the current issue only appears when running finite-shot hermitians, so not necessarily related to the original problem found with Shor.

Thanks @dime10 for the updates! Just updated the description.

**Review by dime10 — APPROVED** [review]
Thanks! Not sure how you guys handle it but I often leave comments in the code for why a tweak like this was necessary to help future developers.

**Comment by multiphaseCFD** [comment]
> Thanks! Not sure how you guys handle it but I often leave comments in the code for why a tweak like this was necessary to help future developers.

Good point. Comments added. Thanks @dime10

**Pull request merged**
