### PR TITLE
Upload wheels to PyPI from GitHub workflows

### PR DESCRIPTION
**Pull request by chaeyeunpark**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by chaeyeunpark** [comment]
Hi @mlxd, it now seems to work (see forked repository which uploads Pennylane-Lightning-Test to test-PyPI well (https://github.com/chaeyeunpark/pennylane-lightning/actions). If this looks okay, I want to change test-PyPI to real PyPI and merge.

**Review by mlxd — COMMENTED** [review]
Hey @chaeyeunpark 
Looks good to me! I think we may update this after the current release cycle (ie once the 0.22.0-dev branch is onboard) to simplify the changing in naming. Do you think that sounds reasonable?

Otherwise, we can merge now and backport the change to the 0.21.0-rc0 branch without the dev name. Happy with whichever you think is best here. I'll approve after this decision.

**Comment by chaeyeunpark** [comment]
Hi @mlxd, the current script does not update the version if it is not a dev version. As it also uploads wheels to PyPI only when it is released or merged into the master, it might be nice to test this feature with the rc build.

**Comment by mlxd** [comment]
> Hi @mlxd, the current script does not update the version if it is not a dev version. As it also uploads wheels to PyPI only when it is released or merged into the master, it might be nice to test this feature with the rc build.

Great, thanks @chaeyeunpark ! I think we can merge this safely on Monday/Tuesday, once we increment the master version to 0.22.0-dev. How does that sound to you?

**Comment by chaeyeunpark** [comment]
@mlxd Yes, that sounds more safe :+1:

**Review by mlxd — APPROVED** [review]
:100:

**Pull request merged**
