### PR TITLE
Lower timeout-minutes.

### PR DESCRIPTION
**Pull request by vincentmr**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**
Windows workflows sometimes get stuck at some step and times out after 6 hours.

**Description of the Change:**
Lower timeout on all workflows to avoid this situation.  

**Benefits:**
Fail faster.

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by AmintorDusko — COMMENTED** [review]
Did you test the wheels we build only when merging to master? (edit: I'm asking because maybe I'm missing something here) The [Wheel::Linux::ARM](https://github.com/PennyLaneAI/pennylane-lightning/blob/c4d43287d1347e5cb3e76170f69cb38f49ea9c5d/.github/workflows/wheel_linux_aarch64.yml) for example can sometimes take [more than 30 min](https://github.com/PennyLaneAI/pennylane-lightning/actions/runs/6240764078). I think we could only limit the Windows runners since they are the problematic ones. What do you think?

**Comment by vincentmr** [comment]
> Did you test the wheels we build only when merging to master? (edit: I'm asking because maybe I'm missing something here) The [Wheel::Linux::ARM](https://github.com/PennyLaneAI/pennylane-lightning/blob/c4d43287d1347e5cb3e76170f69cb38f49ea9c5d/.github/workflows/wheel_linux_aarch64.yml) for example can sometimes take [more than 30 min](https://github.com/PennyLaneAI/pennylane-lightning/actions/runs/6240764078). I think we could only limit the Windows runners since they are the problematic ones. What do you think?

I think it good to have time limit on each job, to set expectations but also avoid wasting time in some cases. While we have an idea how long each job should take, new hires, contributors from other teams and external contributors don't. So I'd like to introduce timeouts and revise them as required. For `wheel_linux_aarch64`, I think you may be right, so I would just increase it to 45 minutes.

**Comment by vincentmr** [comment]
I should note too that there are 30 minutes for building Kokkos and 30 minutes for the wheels, but I can still increase it a bit just in case.

**Comment by mlxd** [comment]
Let's set these as 45 mins -- enough time to have a safety margin, and short enough to kill a task that runs over ahead of the 6 hr window.

**Review by AmintorDusko — APPROVED** [review]
Hey @vincentmr, thank you for that! Please triple-check the CIs building wheels only when merging.

**Review by mlxd — APPROVED** [review]
Thanks @vincentmr

**Pull request merged**
