### PR TITLE
Fix a bug in the generator of DoubleExcitationPlus

### PR DESCRIPTION
**Pull request by maliasadi**
**Context:**
Fix a bug in `applyGeneratorDoubleExcitationPlus`.

### CODE REVIEW

**Review by chaeyeunpark — APPROVED** [review]

**Comment by AmintorDusko** [comment]
Hi @maliasadi. Nice catch!
I wonder why the unit tests didn't get this bug.

**Comment by maliasadi** [comment]
> Hi @maliasadi. Nice catch! I wonder why the unit tests didn't get this bug.

Hmm! It required an improvement in generator tests to catch this bug.

**Comment by chaeyeunpark** [comment]
> Hi @maliasadi. Nice catch! I wonder why the unit tests didn't get this bug.

This bug does not appear when the number of qubits is 4 (the minimum number of wires required by `DoubleExcitationPlus`). As we did not have 4 qubit operators before, I just used the fixed number of qubits = 4 in generator test suits. I now update it and test up to 8 qubits.

**Review by AmintorDusko — APPROVED** [review]
Happy to approve. Once again, nice catch!

**Pull request merged**
