### PR TITLE
Prevent labels from triggering CI

### PR DESCRIPTION
**Pull request by anthayes92**
**Context:**
CI is being triggered by adding any label to a PR in "ready for review" state. This fixes that undesired behaviour 

**Description of the Change:**
Removes the `labeled` PR type from workflows. 

**Benefits:**
Prevents unnecessary resource usage.

**Possible Drawbacks:**
When labels are added that intend to affect CI, a followup commit must be made to trigger the CI

**Related GitHub Issues:**

### Verification:
Added various labels to this PR in a "ready for review" state, no CI checks were triggered as a result.

### CODE REVIEW

**Comment by AmintorDusko** [comment]
Hey @anthayes92, I just merged master to your PR.

**Review by AmintorDusko — APPROVED** [review]
This is all I needed to see:
image
Thank you, @anthayes92!

**Review by vincentmr — APPROVED** [review]
LGTM, but don't forget to update the CHANGELOG.

**Comment by anthayes92** [comment]
> but don't forget to update the CHANGELOG.

Appreciate the reminder, though we typically haven't been adding these GH workflow updates to the changelog since the application code is unchanged

**Pull request merged**
