### PR TITLE
Disable gate dispatcher on x64 MacOS

### PR DESCRIPTION
**Pull request by mlxd**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:** Due to intermittent failures on the CI, this PR disable the dynamic dispatcher on x64 MacOS builds of LightningQubit.

**Description of the Change:** As above.

**Benefits:** Ensures successful builds of the packages for testing and validation across ecosystem.

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by mlxd** [comment]
[sc-61797]

**Review by jay-selby — APPROVED** [review]

**Review by vincentmr — APPROVED** [review]
LGTM too! But isn't this change going to disable the dispatcher on all MacOS platforms (not just x64)?

**Comment by mlxd** [comment]
> LGTM too! But isn't this change going to disable the dispatcher on all MacOS platforms (not just x64)?

There's no dispatcher support on anything but x64, so it won't affect the ARM builds in any way, so I think it's fine. If we intend to add ARM intrinsics later, we'll need to restructure the dispatcher anyway, so that's probably the best time to re-evaluate.

**Comment by vincentmr** [comment]
> > LGTM too! But isn't this change going to disable the dispatcher on all MacOS platforms (not just x64)?
> 
> There's no dispatcher support on anything but x64, so it won't affect the ARM builds in any way, so I think it's fine. If we intend to add ARM intrinsics later, we'll need to restructure the dispatcher anyway, so that's probably the best time to re-evaluate.

Ah, yes, of course. All good then.

**Comment by mlxd** [comment]
Thanks @vincentmr and @jay-selby

**Pull request merged**
