### PR TITLE
Modify pybind11 classes scope in modules

### PR DESCRIPTION
**Pull request by mlxd**
**Context:** When using Lightning as a library, having globally-exposed methods can cause issues when using the templated types with other external packages (see [here](https://github.com/pybind/pybind11/blob/master/docs/advanced/classes.rst#module-local-class-bindings) for details). In this case, ensuring the classes are exposed locally at the module level only helps avoid such issues as `ImportError: generic_type: type "MyType" is already registered!`. This PR helps to ensure such problems are avoided.

**Description of the Change:** Modifies Lightning bound classes to have local scope to Python modules only.

**Benefits:** Allows easier extensibility of the Lightning functionality for dependent classes and methods.

**Possible Drawbacks:** Disallows direct interoperability and conversion to Python types.

**Related GitHub Issues:**

### CODE REVIEW

**Comment by mlxd** [comment]
Note, following the partitioning rules of [here](https://github.com/pybind/pybind11/blob/master/docs/advanced/misc.rst#partitioning-code-over-multiple-extension-modules) may be more sensible in the long run, keeping separate types allows more extensibility while lowering the maintenance burden for disparate repositories.

**Review by AmintorDusko — APPROVED** [review]
Very nice! Thanks for that!

**Review by chaeyeunpark — APPROVED** [review]
Happy to approve this.

**Comment by mlxd** [comment]
Thanks all.

**Pull request merged**
