### PR TITLE
Accel/expval

### PR DESCRIPTION
**Pull request by vincentmr**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [x] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [x] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**
In the LKokkos backend, there are two ways to implement expectation values:

1. Copy the statevector, apply the observable to the copy, compute the expectation value with a BLAS-like inner product.
2. Accumulate the expectation value on-the-fly, applying the observable to a portion of the statevector.

The first method is currently in use, but is wasteful in a couple ways:

- The statevector copy can require a lot of memory, which means running out with one or two fewer qubits depending on the system.
- Computational efficiency is asymptotically memory-bound and reduce operations can achieve roughly twice the bandwidth of for loop operations on Nvidia devices, for example, which favors on-the-fly implementations.

A simple benchmarking script like the one below yields, for 29 qubits (on Perlmutter's A100)

1. 0.330 sec.
2. 0.012 sec.

i.e. a 27.5x speed-up.

```
import pennylane as qml
import time

n_wires = 29
n_repeat = 100

dev = qml.device("lightning.kokkos", wires=n_wires)

@qml.qnode(dev)
def circuit():
    return qml.expval(qml.PauliZ(n_wires//2))

t0 = time.time()
for _ in range(n_repeat):
    circuit()
dt = (time.time() - t0)/n_repeat
print(f"{dt}")
```
 
**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by vincentmr** [comment]
In support of this PR, I made a [gist](https://gist.github.com/vincentmr/0a33bb4d3b779556ae10042049a3589c) that benchmarks `expval` on a CPU (`OMP_NUM_THREADS=64`) and a GPU (A100). The results are generally faster, especially the 1- and 2-qubit operators above 20 qubits. In the following figures, `inner` and `team` stand for the inner-product-based and `TeamPolicy` (this PR) algorithms respectively; `first` stands for targeting low-index qubits (only `first` shown since timings are similar across `first`, `mid` and `last` targets); `1`, `2`, `3` stand for the number of wires targeted by the `Hermitian` unitary. The timings for 1-qubit `Hermitian` unitaries are similar to that of named gates (e.g. `PauliZ`) with an equal number of wires. 

benchmarks_CPU
benchmarks_GPU

**Comment by vincentmr** [comment]
Bonus with LKokkos benchmarks run on LUMI's AMD cards
benchmarks_HIP

**Review by mlxd — DISMISSED** [review]
:100:

**Review by mlxd — APPROVED** [review]
Happy with the revision. Thanks @vincentmr

**Pull request merged**
