### PR TITLE
Sample minimal subset of wires on LightningQubit

### PR DESCRIPTION
**Pull request by vincentmr**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [x] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [x] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [x] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**
With enough qubits and shots, it is wasteful to generate samples on all wires.

**Description of the Change:**
LightningQubit calls `generate_samples(wires)` on a minimal subset of wires when executing in finite-shot mode.

**Benefits:**
Faster sampling and execution.
We perform a simple benchmark of 
```python
@qml.qnode(dev)
def f():
    return qml.sample(wires)
```
where `wires` takes values `[0]`, `range(0, nq//2)` and `range(0, nq)`. For a large enough number of qubits and/or samples, we observe good speed-ups (up to 8x) for the 1-wire and half-wire cases. As expected, the all-wire case yields ~1x for all simulations.
 
speedup_1w
speedup_whf
speedup_wall

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by AmintorDusko — COMMENTED** [review]
The performance is excellent. Is there an actual coverage issue, or is codecov just being a nuisance?

**Comment by vincentmr** [comment]
> The performance is excellent. Is there an actual coverage issue, or is codecov just being a nuisance?

The patch cov is 100%, but project cov is low because C++ tests didn't run.

**Review by LuisAlfredoNu — APPROVED** [review]
Nice job. The improvement in the performance is good

**Comment by vincentmr** [comment]
[sc-65127]

**Pull request merged**
