### PR TITLE
Fix stopping condition thresholds

### PR DESCRIPTION
**Pull request by mlxd**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [x] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [x] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [x] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:** This fixes the matrix vs decomposition split in the stopping condition for the included aggregate template operations.

**Description of the Change:** Avoids building matrices beyond the given thresholds defined in the stopping condition.

**Benefits:** Significantly reduced runtime overheads for larger systems.

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by mlxd** [comment]
[sc-56165]

**Review by AmintorDusko — CHANGES_REQUESTED** [review]
Thank you for the fix. Could you please add a test that covers the previously wrong behavior?

**Review by vincentmr — APPROVED** [review]
Looks good to me, thanks @mlxd .

**Comment by AmintorDusko** [comment]
Hey @mlxd, nice work! Please re-tag me when CIs are successful.

**Review by AmintorDusko — APPROVED** [review]
Looks good!

**Pull request merged**
