### PR TITLE
Fix the failed observable serialization unit tests

### PR DESCRIPTION
**Pull request by maliasadi**
PR https://github.com/PennyLaneAI/pennylane/pull/5475 led to LQ and LK serialization unit tests failures. This PR updates them to pass on CIs.

### CODE REVIEW

**Review by vincentmr — APPROVED** [review]
If that works, no blocker from me. Thanks @maliasadi !

**Comment by multiphaseCFD** [comment]
Thanks @maliasadi ! Do we also want to turn on mgpu tests?

**Review by mudit2812 — APPROVED** [review]

**Comment by mudit2812** [comment]
Device tests are still failing with LGPU and LK. Let's figure out if the issue is on the lightning side or PL side before merging this.

**Comment by tomlqc** [comment]
[sc-61588]

**Pull request merged**
